### PR TITLE
feat: add linter

### LINKED ISSUE #102: Choose, integrate and setup a linter
## Description:
Now that we're working together on the project, it would be nice to have a linter.

## Todo:
- [x] Choose a linter from the following solutions:
    - [standardrb](https://github.com/standardrb/standard)
    - [omakase](https://github.com/rails/rubocop-rails-omakase)
- [x] Integrate a linter
- [x] Set up automated linting after push with GitHub Actions

### PR DESCRIPTION
**Pull request by alallema**
# General

Fixes #102

# Description

This PR adds a new linter to the project. omakase was chosen for its ease of use, even though it does not have a lot of star at the moment, probably because version 1 was only released last month.

# Changes

- Addition of the omakase gem ()
- Addition of the github action worklow file
- Addition of all the changes made by the linter
- Update README.md file

# Note for the reviewer

I've added a special rule to keep all double quotes. It also seems that you don't particularly like spaces, most of the linter modifications are their addition but this can be modified if you wish. 
⚠️ Code modifications were made in these files:
- [test.yaml](https://github.com/louije/court-message/pull/107/files#diff-95557d53bf91069e59d82b9d8fcfaf52ec84a762858983edd5ef3c9b3e4c8191)
- [rubocop.yml](https://github.com/louije/court-message/pull/107/files#diff-4f894049af3375c2bd4e608f546f8d4a0eed95464efcdea850993200db9fef5c)
- [Gemfile](https://github.com/louije/court-message/pull/107/files#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55f)
- [Gemfile.lock](https://github.com/louije/court-message/pull/107/files#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731f)

### CODE REVIEW

**Comment by louije** [comment]
Looks great, I would remove the standard gem and its configuration file too!

**Comment by louije** [comment]
(Also: didn't see the lil "WIP" at the top. I'll behave.)

**Comment by alallema** [comment]
> (Also: didn't see the lil "WIP" at the top. I'll behave.)
That's on me I forgot to remove it before requested you

**Comment by alallema** [comment]
> Looks great, I would remove the standard gem and its configuration file too!

Done ✅

**Pull request merged**
